export const LOGIN = 'LOGIN';
export const CREATE_PROBLEM = 'CREATE_PROBLEM';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_COORDINATES = 'SET_COORDINATES';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const INIT_PROBLEMS_LIST = 'INIT_PROBLEMS_LIST';
export const ADD_PROBLEM = 'ADD_PROBLEM';
